name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download
      
      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      - name: Install taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build proto files
        run: task --taskfile HailowProto/Taskfile.yml build_go

      - name: Run tests
        run: go test ./cmd/... ./internal/... ./pkg/...

      - name: Build server
        run: go build ./cmd/server
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download
      
      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      - name: Install taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build proto files
        run: task --taskfile HailowProto/Taskfile.yml build_go

      - name: Run tests
        run: go test ./cmd/... ./internal/... ./pkg/...
